muachung/Controllers/MuaChungManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using muachung.Models;
using Microsoft.AspNet.Identity;

namespace MuaChungManage.Controllers
{
    public class MuaChungManageController : Controller
    {
        private muachungEntities db = new muachungEntities();

        //
        // GET: /MuaChungManage/

        // Danh sách sản phẩm hiện tại

        public ActionResult Index()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            var product = db.SP_GET_PRODUCTS_ALL();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            return View(product);
            //return View(db.Products.Where(x => x.Deleted == false).OrderBy(x => x.ProductId).ToList());
        }


        // Danh sách sản phẩm đã bị xóa

        public ActionResult DeletedProduct()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            var delProduct = db.SP_GET_PRODUCTS_DELETED();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            return View(delProduct);
        }
        


        //
        // GET: /MuaChungManage/Details/5

        public ActionResult Details(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /MuaChungManage/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MuaChungManage/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Product product, HttpPostedFileBase Images1, HttpPostedFileBase Images2, HttpPostedFileBase Images3)
        {
            HttpContext.Server.ScriptTimeout = 1000;
            if (ModelState.IsValid)
            {
                User user = new User();

                user = db.Users.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
                product.UserId = user.UserId;
                product.Views = 123;
                product.Created = DateTime.Now;
                if (Images1 != null)
                {
                    string name = System.IO.Path.GetFileName(Images1.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images1.SaveAs(path);
                    product.Images1 = Images1.FileName;
                }
                if (Images2 != null)
                {
                    string name = System.IO.Path.GetFileName(Images2.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images2.SaveAs(path);
                    product.Images2 = Images2.FileName;
                }
                if (Images3 != null)
                {
                    string name = System.IO.Path.GetFileName(Images3.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images3.SaveAs(path);
                    product.Images3 = Images3.FileName;
                }

                var productid = db.Products.Where(p => p.ProductId == product.ProductId).Count();
                if (productid > 0)
                {
                    ModelState.AddModelError("", "* Product Id Userd");
                }
                else
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(product);
        }

        //
        // GET: /MuaChungManage/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /MuaChungManage/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase Images1, HttpPostedFileBase Images2, HttpPostedFileBase Images3)
        {
            HttpContext.Server.ScriptTimeout = 1000;
            if (ModelState.IsValid)
            {
                product.Modified = DateTime.Now;
                if (Images1 != null)
                {
                    string name = System.IO.Path.GetFileName(Images1.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images1.SaveAs(path);
                    product.Images1 = Images1.FileName;
                }
                if (Images2 != null)
                {
                    string name = System.IO.Path.GetFileName(Images2.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images2.SaveAs(path);
                    product.Images2 = Images2.FileName;
                }
                if (Images3 != null)
                {
                    string name = System.IO.Path.GetFileName(Images3.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Upload/"), name);
                    Images3.SaveAs(path);
                    product.Images3 = Images3.FileName;
                }

                 db.Entry(product).State = EntityState.Modified;
                 db.SaveChanges();
                 return RedirectToAction("Index");
            }
            return View(product);
        }

        //
        // GET: /MuaChungManage/Delete/5

        public ActionResult Delete(int id)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /MuaChungManage/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            product.Deleted = true;
            db.SaveChanges();
            return Json(new { result = true });
        }

        public ActionResult UnDelete(int id)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /MuaChungManage/UnDelete/5

        [HttpPost, ActionName("UnDelete")]
        public ActionResult UnDeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            product.Deleted = false;
            db.SaveChanges();
            return Json(new { result = true });
        }

        /// <summary>
        /// Kiểm tra tồn tại Product ID
        /// </summary>
        /// <param name="productid"></param>
        /// <returns></returns>
        public JsonResult CheckProductId(string productid)
        {
            var product = db.Products.Where(x => x.ProductId == productid).Count();
            if (product > 0)
                return Json(false);
            else
                return Json(true);
        }

        #region --Check, delete and active product--

        /// <summary>
        /// Set sản phẩm Hot
        /// </summary>
        /// <param name="idcourse"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult IsActive(int? userid)
        {
            var hl = db.Products.FirstOrDefault(x => x.Id == userid);
            hl.ProductHot = false;
            db.Entry(hl).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new { result = true });
        }

        /// <summary>
        /// Bỏ Set sản phẩm hot
        /// </summary>
        /// <param name="idcourse"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult UnActive(int? userid)
        {
            var hl = db.Products.FirstOrDefault(x => x.Id == userid);
            hl.ProductHot = true;
            db.Entry(hl).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new { result = true });
        }

        /// <summary>
        ///  Set sản phẩm hot hoặc sản phẩm thường
        /// </summary>
        /// <param name="userids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult IsActiveSeleted(string userids)
        {
            string[] arrUser = userids.Split(',');
            int count = 0;
            for (int i = 0; i < arrUser.Length; i++)
            {
                var ids = arrUser[i];
                var id = Convert.ToInt32(ids);
                var userid = db.Products.FirstOrDefault(x => x.Id == id);
                if (userid.ProductHot == false)
                {
                    userid.ProductHot = true;
                    db.SaveChanges();
                    count++;
                }
                else
                {
                    count++;
                }

            }
            return Json(new { result = true });
        }

        /// <summary>
        /// Xóa những bản ghi đã được chọn
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCheckAll(string ids)
        {
            string[] course = ids.Split(',');
            int count = 0;
            for (int i = 0; i < course.Length; i++)
            {

muachung/Views/MuaChungManage/Create.cshtml
@model muachung.Models.Product
@using muachung.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

<h2 id="create">Create</h2>

@using (Html.BeginForm("Create", "MuaChungManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <div class="col-md-12">
        <div class="box box-warning">
            <div class="box-body">
                <form role="form">

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ProductId)</label>
                        @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control", @id = "productid", @placeholder = "Nhập mã sản phẩm" })
                        @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "errorrmessage" })
                        <p id="result"></p>
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Name)</label>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Nhập tên sản phẩm" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "errorrmessage" })
                    </div>


                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Cost)</label>
                        @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", @placeholder = "Nhập giá sản phẩm", @pkid = "cost" }) <p class="vnd">VND</p>
                        @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.CostSale)</label>
                        @Html.TextBoxFor(model => model.CostSale, new { @class = "form-control", @placeholder = "Nhập giá đã giảm", @pkid = "cost" }) <p class="vnd">VND</p>
                        @Html.ValidationMessageFor(model => model.CostSale, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ShopName)</label>
                        @Html.TextBoxFor(model => model.ShopName, new { @class = "form-control", @placeholder = "Nhập tên cửa hàng" })
                        @Html.ValidationMessageFor(model => model.ShopName, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Address)</label>
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control", @placeholder = "Nhập địa chỉ", @rows = 10 })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Information)</label>
                        @Html.TextAreaFor(model => model.Information, new { @class = "form-control", @placeholder = "Nhập thông tin sản phẩm" })
                        @Html.ValidationMessageFor(model => model.Information, "", new { @class = "errorrmessage" })
                    </div>


                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images1)</label>
                        @Html.TextBoxFor(model => model.Images1, null, new { type = "file", name = "Images", id = "Images" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images2)</label>
                        @Html.TextBoxFor(model => model.Images2, null, new { type = "file", name = "Images", id = "Images" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images3)</label>
                        @Html.TextBoxFor(model => model.Images3, null, new { type = "file", name = "Images", id = "Images" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ProductHot)</label>
                        @Html.CheckBoxFor(model => model.ProductHot, new { @class = "iCheck-helper" })
                        <em>(Select product hot)</em>
                    </div>

    <input type="submit" class="btn btn-info btn-flat" id="taomoi" value="Create" />
    <a href="@Url.Action("Index", "MuaChungManage")" class="btn btn-default btn-flat" id="taomoi">Back to Manage page</a>
</form>
            </div>
        </div>
    </div>
}

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    $("#productid").change(function () {
        var name = $("#productid").val();
        var status = $("#result");
        status.html("Check ProductId....");
        $.post("/MuaChungManage/CheckProductId", { productid: name },
                function (data) {
                    if (data == true) {
                        status.html("OK").addClass("text-green");
                    } else {
                        status.html("ProductID used").addClass("text-red");
                    }
                });
    });
</script>

muachung/Views/MuaChungManage/DeletedProduct.cshtml
@model IEnumerable<muachung.Models.SP_GET_PRODUCTS_DELETED_Result>

@{
    ViewBag.Title = "Danh sách sản phẩm đã bị xóa";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

@section SlideBar{
    <li class="active">@ViewBag.Title</li>
}

<div class="col-xs-12" style="margin-bottom: 10px;">
    <div class="col-xs-2 pull-right">
        <button class="btn btn-block btn-danger btn-flat pull-right" id="phucHoiMulti">Phục hồi</button>
    </div>
</div>
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Chọn</th>
                        <th>Mã sản phẩm</th>
                        <th>Tên sản phẩm</th>
                        <th>Giá (gốc)</th>
                        <th>Giá (hạ)</th>
                        <th>Ảnh SP</th>
                        <th>Hot</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
                    {
                        <tr>
                            <td><input type="checkbox" name="@item.Data.Name" value="@item.Data.Id" /></td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.ProductId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Cost)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.CostSale)
                            </td>
                            <td>
                                <img src="~/Content/Upload/@item.Data.Images1" alt="" height="50" width="50" style="border-radius: 25px;" />
                            </td>
                            <td>
                                @if (item.Data.ProductHot == true)
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.Id" title="Sản phẩm hot" class="hoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:green;"></i></a>

                                }
                                else
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.Id" title="Sản phẩm thường" class="khonghoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:darkgray;"></i></a>
                                }
                            </td>
                            <td style="width: 70px;">
                                <a href="@Url.Action("UnDelete", "MuaChungManage", new { id = item.Data.Id })" name="@item.Data.Name" class="Phuchoi" pkid="@item.Data.Id">Phục hồi</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>Mã sản phẩm</th>
                        <th>Tên sản phẩm</th>
                        <th>Giá (gốc)</th>
                        <th>Giá (hạ)</th>
                        <th>Ảnh SP</th>
                        <th>Hot</th>
                        <th>Thao tác</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- /.col -->

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    // Phục hồi nhiều sản phẩm trên trang

    $('#phucHoiMulti').on("click", function () {
        var selected = [];
        var selectedName = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr('value');
            var name = jQuery(this).attr('name');
            selected.push(data);
            selectedName.push(name);
        });
        var arr = selected.join(',');
        var nameArr = selectedName.join(', ');
        console.log(arr);
        bootbox.confirm("Bạn có thực sự muốn phục hồi sản phẩm ( " + nameArr + " ) ?", function (result) {
            title: "Xác nhận phục hồi !";
            if (result == true) {
                $.post("/MuaChungManage/UnDeleteCheckAll", { ids: arr }, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công sản phẩm ");
                        location.href = "/MuaChungManage/Index";
                    }

                });
            }
        });
        return false;
    });

    // Phục hồi 1 sản phẩm

    $(".Phuchoi").click(function () {
        var data = jQuery(this).attr('pkid');
        var name = jQuery(this).attr('name');
        console.log(data);
        bootbox.confirm("Bạn có thực sự muốn phục hồi sản phẩm " + name + "?", function (result) {
            title: "Xác nhận phục hồi !";
            if (result == true) {
                $.post("/MuaChungManage/UnDelete/" + data, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công sản phẩm " + name);
                        location.href = "/MuaChungManage/Index";
                    }

                });
            }
        });
        return false;
    });

    $(".hoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("IsActive", "MuaChungManage")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            }

        });
    });

    $(".khonghoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("UnActive", "MuaChungManage")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });


    $(".kichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted" , "MuaChungManage")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

    $(".bokichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted" , "MuaChungManage")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

</script>

muachung/Views/MuaChungManage/Edit.cshtml
@model muachung.Models.Product
@using muachung.Models

@{
    ViewBag.Title = "Sửa thông tin sản phẩm";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<h2 id="create">@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "MuaChungManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.Created)
    @Html.HiddenFor(model => model.Images1)
    @Html.HiddenFor(model => model.Images2)
    @Html.HiddenFor(model => model.Images3)
    @Html.HiddenFor(model => model.Views)

    <div class="col-md-12">
        <div class="box box-warning">
            <div class="box-body">
                <form role="form">

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ProductId)</label>
                        @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control", @id = "productid", @placeholder = "Enter Product ID..." })
                        @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "errorrmessage" })
                        <p id="result"></p>
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Name)</label>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Enter name product..." })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Cost)</label>
                        @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", @placeholder = "Enter cost...", @id = "cost" }) <p class="vnd">VND</p>
                        @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.CostSale)</label>
                        @Html.TextBoxFor(model => model.CostSale, new { @class = "form-control", @placeholder = "Enter cost sale...", @id = "cost" }) <p class="vnd">VND</p>
                        @Html.ValidationMessageFor(model => model.CostSale, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Information)</label>
                        @Html.TextAreaFor(model => model.Information, new { @class = "form-control", @placeholder = "Enter information...", @rows = 6 })
                        @Html.ValidationMessageFor(model => model.Information, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ProductHot)</label>
                        @Html.CheckBoxFor(model => model.ProductHot, new { @class = "iCheck-helper" })
                        <em>(Select product hot)</em>
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.ShopName)</label>
                        @Html.TextAreaFor(model => model.ShopName, new { @class = "form-control", @placeholder = "Enter address and required..." })
                        @Html.ValidationMessageFor(model => model.ShopName, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Address)</label>
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control", @placeholder = "Enter address and required..." })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "errorrmessage" })
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images1)</label>
                        @Html.TextBoxFor(model => model.Images1, new { type = "file", name = "Images1", id = "Images1" })
                        <h3><img style="border: 1px solid gray; padding: 3px;" src="~/Content/Upload/@Model.Images1" alt="" height="80" width="80" /></h3>
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images2)</label>
                        @Html.TextBoxFor(model => model.Images2, new { type = "file", name = "Images2", id = "Images2" })
                        <h3><img style="border: 1px solid gray; padding: 3px;" src="~/Content/Upload/@Model.Images2" alt="" height="80" width="80" /></h3>
                    </div>

                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images3)</label>
                        @Html.TextBoxFor(model => model.Images3, new { type = "file", name = "Images3", id = "Images3" })
                        <h3><img style="border: 1px solid gray; padding: 3px;" src="~/Content/Upload/@Model.Images3" alt="" height="80" width="80" /></h3>
                    </div>

                    <div class="form-group">
                        <label>Người hiệu chỉnh lần cuối:</label>
                        @Html.DisplayFor(model => model.User.Username)
                        @Html.ValidationMessageFor(model => model.User.Username, "", new { @class = "errorrmessage" })
                    </div>

                    @if (Model.Created != null && Model.Modified == null)
                    {
                        <div class="form-group">
                            <label>Ngày khởi tạo:</label>
                            @Html.DisplayFor(model => model.Created)
                            @Html.ValidationMessageFor(model => model.Created, "", new { @class = "errorrmessage" })
                        </div>
                    }

                    @if (Model.Modified != null)
                    {
                        <div class="form-group">
                        <label>Hiệu chỉnh lần cuối:</label>
                        @Html.DisplayFor(model => model.Modified)
                        @Html.ValidationMessageFor(model => model.Modified, "", new { @class = "errorrmessage" })
                    </div>
                    }

                    <input type="submit" class="btn btn-info btn-flat" id="taomoi" value="Save" />
                    <a href="@Url.Action("Index", "MuaChungManage")" class="btn btn-default btn-flat" id="taomoi">Back to Manage page</a>
                </form>
            </div>
        </div>
    </div>
}

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    $("#productid").change(function () {
        var name = $("#productid").val();
        var status = $("#result");
        status.html("Check ProductId....");
        $.post("/MuaChungManage/CheckProductId", { productid: name },
                function (data) {
                    if (data == true) {
                        status.html("OK").addClass("text-green");
                    } else {
                        status.html("ProductID used").addClass("text-red");
                    }
                });
    });
</script>