muachung/Controllers/AccountLoginController.cs
using muachung.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace muachung.Controllers
{
    public class AccountLoginController : Controller
    {
        muachungEntities context = new muachungEntities();
        // GET: Account

        // Hàm kiểm tra tên tài khoản và mật khẩu đăng nhập
        public bool CheckValid(string usn, string pw)
        {
            bool CheckValid = false;
            using (var context = new muachungEntities())
            {
                var user = context.Users.FirstOrDefault(x => x.Username == usn);
                if (user != null)
                {
                    try
                    {
                        if (user.Username == usn)
                        {
                            if (user.Password == pw)
                            {
                                CheckValid = true;
                            }
                        }
                    }
                    catch
                    {
                        CheckValid = false;
                    }
                }
            }
            return CheckValid;
        }

        // Hàm đăng nhập (lồng hàm kiểm tra CheckValid)
        public ActionResult Login()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {
            if (CheckValid(user.Username, user.Password))
            {
                FormsAuthentication.SetAuthCookie(user.Username, user.RememberMe);
                Session.Add("S_User", user);
                ViewBag.active = user.Username;
                return RedirectToAction("Index", "MuaChungManage");
            }
            else
            {
                ModelState.AddModelError("", "Mat khau khong chinh xac");
            }
            return View(user);
        }
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Session.Remove("S_User");
            return RedirectToAction("Index", "Home");
        }
        
        // Hàm JSON trả về kết quả kiểm tra tên đăng nhập
        [HttpPost]
        public JsonResult CheckUser(FormCollection form)
        {
            System.Threading.Thread.Sleep(1000);
            string name = form["username"];
            var user = context.Users.Where(x => x.Username == name).Count();
            if (user > 0)
            {
                return Json(new { result = true });
            }
            else
            {
                return Json(new { result = false });
            }
        }

        //Hàm Trả về tên người dùng hiện tại và layout người dùng
        public ActionResult GetUserActive(string view = "")
        {
            User user = new User();
            user = (User)Session["S_User"];
            var model = context.Users.Where(x => x.Username.Equals(user.Username)).FirstOrDefault();
            return PartialView(view, model);
        }

        public ActionResult GetAvatar(string id = "", string view = "")
        {
            User user = new User();
            if (String.IsNullOrEmpty(id))
                id = User.Identity.Name;
            //user = null thì lấy thông tin của user đang đăng nhập
            if (id != null)
            {
                user = context.Users.Where(x => x.Username.Equals(id)).FirstOrDefault();
            }
            else
            {
                int ids = int.Parse(id);
                user = context.Users.Where(x => x.UserId == ids).FirstOrDefault();
            }

            return PartialView(view, user);
        }

	}
}

muachung/Views/AccountLogin/Login.cshtml
@model muachung.Models.User

@{
    Layout = null;
}

@* Created by KhanhThietBi - www.fb.com/NeedleKane *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Bootstrap Login Form</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="~/Content/css/styles.css" rel="stylesheet">
</head>
<body>
    <!--login modal-->
    <div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" style="margin-top: 150px; width: 400px">
            <div class="modal-content">
                <div class="modal-header" align="center">
                    <img src="~/Content/images/apple.png" width="120px" />
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <form class="form col-md-12 center-block" method="post">
                                <div class="form-group">
                                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control ", @placeholder = "Điền thông tin tài khoản", @id = "username" })
                                </div>
                                <p id="checkname"></p>
                                <div class="form-group">
                                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Điền mật khẩu", @id = "password" })
                                </div>
                                <div class="form-group">
                                    <button class="btn pull-right" style="background: #608097; color: white;">Đăng nhập</button>
                                </div>
                            </form>
                        }
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <!-- script references -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>

    <!-- jQuery 2.1.3 -->
    <script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>

    <script>
        $("#username").change(function () {
            var name = $("#username").val();
            var status = $("#checkname");
            status.html("Đang kiểm tra tên đang nhập...");
            $.ajax({
                url: '@Url.Action("CheckUser", "AccountLogin")',
                type: 'post',
                data: { username: name }
            }).success(function (data) {
                if (data.result == true) {
                    status.html("Tên đăng nhập hợp lệ");
                }
                else {
                    status.html("Tên đăng nhập không tồn tại");
                }
            });
        });
    </script>

</body>
</html>

@* Author: www.fb.com/NeedleKane *@