muachung/Controllers/AccountManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using muachung.Models;

namespace muachung.Controllers
{
    public class AccountManagerController : Controller
    {
        private muachungEntities db = new muachungEntities();

        // GET: /AccountManager/
        public ActionResult Index()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            var activeUser = db.SP_GET_USERS_ALL();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            return View(activeUser);
        }

        public ActionResult DeletedUser()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            var deletedUser = db.SP_GET_USERS_DELETED();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            return View(deletedUser);
        }

        // GET: /AccountManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: /AccountManager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /AccountManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(User user, HttpPostedFileBase Avatar)
        {
            if (ModelState.IsValid)
            {
                if (Avatar != null)
                {
                    string name = System.IO.Path.GetFileName(Avatar.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/UserAvatar/"), name);
                    Avatar.SaveAs(path);
                    user.Avatar = Avatar.FileName;
                }
                else
                {
                    user.Avatar = "default.png";
                }
                var result = db.Users.Where(x => x.Username == user.Username && x.Active == true).Count();
                if (result > 0)
                {
                    ModelState.AddModelError("", "Tên tài khoản đã tồn tại");
                }
                else
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(user);
        }

        // GET: /AccountManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /AccountManager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user, HttpPostedFileBase avatar)
        {
            if (ModelState.IsValid)
            {
                if (avatar != null)
                {
                    string name = System.IO.Path.GetFileName(avatar.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/UserAvatar"), name);
                    avatar.SaveAs(path);
                    user.Avatar = avatar.FileName;
                }
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: /AccountManager/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /AccountManager/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            user.Active = false;
            db.SaveChanges();
            return Json(new { result = true });
        }

        // GET: /AccountManager/UnDelete/5
        public ActionResult UnDelete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /AccountManager/UnDelete/5
        [HttpPost, ActionName("UnDelete")]
        public ActionResult UnDeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            user.Active = true;
            db.SaveChanges();
            return Json(new { result = true });
        }

        /// <summary>
        ///  Cho phép user hoạt động hoặc ngừng hoạt động khi chọn ở ô checkbox
        /// </summary>
        /// <param name="userids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult IsActiveSeleted(string userids)
        {
            string[] arrUser = userids.Split(',');
            int count = 0;
            for (int i = 0; i < arrUser.Length; i++)
            {
                var ids = arrUser[i];
                var id = Convert.ToInt32(ids);
                var userid = db.Users.FirstOrDefault(x => x.UserId == id);
                if (userid.Active == false)
                {
                    userid.Active = true;
                    db.SaveChanges();
                    count++;
                }
                else
                {
                    userid.Active = false;
                    db.SaveChanges();
                    count++;
                }

            }
            return Json(new { result = true });
        }

        /// <summary>
        /// Xóa những bản ghi đã được chọn
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCheckAll(string ids)
        {
            string[] course = ids.Split(',');
            int count = 0;
            for (int i = 0; i < course.Length; i++)
            {
                var id = Convert.ToInt32(course[i]);
                var userid = db.Users.FirstOrDefault(x => x.UserId == id);
                userid.Active = false;
                db.SaveChanges();
                count++;
            }
            return Json(new { result = true });
        }

        [HttpPost]
        public JsonResult UnDeleteCheckAll(string ids)
        {
            string[] course = ids.Split(',');
            int count = 0;
            for (int i = 0; i < course.Length; i++)
            {
                var id = Convert.ToInt32(course[i]);
                var userid = db.Users.FirstOrDefault(x => x.UserId == id);
                userid.Active = true;
                db.SaveChanges();
                count++;
            }
            return Json(new { result = true });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

muachung/Views/AccountManager/Create.cshtml
@model muachung.Models.User

@{
    ViewBag.Title = "Tạo người dùng mới";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

<h2 align="center" style="text-transform: uppercase; line-height:40px;">@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "AccountManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Avatar, null, new { type = "file", name = "Avatar", id = "Avatar" })
                <h3><img style="border: 1px solid gray; padding: 3px;" src="~/Content/UserAvatar/default.png" alt="" height="80" width="80" /></h3>
                @Html.ValidationMessageFor(model => model.Avatar)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

muachung/Views/AccountManager/Delete.cshtml
@model muachung.Models.User

@{
    ViewBag.Title = "Xóa người dùng";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

<h2 align="center" style="text-transform: uppercase; line-height:40px;">@ViewBag.Title</h2>

<div>
    <h4>Xóa người dùng: @Model.Username ?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

muachung/Views/AccountManager/DeletedUser.cshtml
@model IEnumerable<muachung.Models.SP_GET_USERS_DELETED_Result>

@{
    ViewBag.Title = "Danh sách người dùng đã bị xóa";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

@section SlideBar{
    <li class="active">@ViewBag.Title</li>
}

<div class="col-xs-12" style="margin-bottom: 10px;">
    <div class="col-xs-2 pull-right">
        <button class="btn btn-block btn-danger btn-flat pull-right" id="phucHoiMulti">Phục hồi</button>
    </div>
</div>
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>Mã người dùng</th>
                        <th>Tên tài khoản</th>
                        <th>Hình đại diện</th>
                        <th>Trạng thái kích hoạt</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
                    {
                        <tr>
                            <td><input type="checkbox" name="@item.Data.Username" value="@item.Data.UserId" /></td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.UserId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Username)
                            </td>
                            <td>
                                <img src="~/Content/UserAvatar/@item.Data.Avatar" alt="" height="50" width="50" style="border-radius: 25px;" />
                            </td>
                            <td>
                                @if (item.Data.Active == true)
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.UserId" title="Người dùng hiện hành" class="hoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:green;"></i></a>

                                }
                                else
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.UserId" title="Người dùng đã bị xóa" class="khonghoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:darkgray;"></i></a>
                                }
                            </td>
                            <td style="width: 70px;">
                                <a href="@Url.Action("UnDelete", "AccountManager", new { id = item.Data.UserId })" name="@item.Data.Username" class="PhucHoi" pkid="@item.Data.UserId">Phục hồi</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>Mã người dùng</th>
                        <th>Tên tài khoản</th>
                        <th>Hình đại diện</th>
                        <th>Trạng thái kích hoạt</th>
                        <th>Thao tác</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- /.col -->

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    // Phục hồi nhiều tài khoản trên trang

    $('#phucHoiMulti').on("click", function () {
        var selected = [];
        var selectedName = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr('value');
            var name = jQuery(this).attr('name');
            selected.push(data);
            selectedName.push(name);
        });
        var arr = selected.join(',');
        var nameArr = selectedName.join(', ');
        console.log(arr);
        bootbox.confirm("Bạn có thực sự muốn phục hồi tài khoản ( " + nameArr + " ) ?", function (result) {
            title: "Xác nhận xóa !";
            if (result == true) {
                $.post("/AccountManager/UnDeleteCheckAll", { ids: arr }, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công tài khoản ");
                        location.href = "/AccountManager/Index";
                    }

                });
            }
        });
        return false;
    });

    // Phục hồi  1 tài khoản

    $(".PhucHoi").click(function () {
        var data = jQuery(this).attr('pkid');
        var name = jQuery(this).attr('name');
        console.log(data);
        bootbox.confirm("Bạn có thực sự muốn phục hồi tài khoản " + name + "?", function (result) {
            title: "Xác nhận xóa !";
            if (result == true) {
                $.post("/AccountManager/UnDelete/" + data, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công tài khoản " + name);
                        location.href = "/AccountManager/Index";
                    }

                });
            }
        });
        return false;
    });
</script>

muachung/Views/AccountManager/Details.cshtml
@model muachung.Models.User

@{
    ViewBag.Title = "Thông tin người dùng";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

<h2 align="center" style="text-transform: uppercase; line-height:40px;">@ViewBag.Title</h2>

<div>
    <h4>Thông tin người dùng: @Model.Username</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

muachung/Views/AccountManager/Edit.cshtml
@model muachung.Models.User

@{
    ViewBag.Title = "Cập nhật thông tin người dùng";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}



@using (Html.BeginForm("Edit", "AccountManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cập nhật thông tin người dùng: @Model.Username</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.Avatar)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Avatar, new { type = "file", name = "Avatar", id = "Avatar" })
                <h3><img id="pic" style="border: 1px solid gray; padding: 3px;" src="~/Content/UserAvatar/@Model.Avatar" alt="" height="80" width="80" /></h3>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

muachung/Views/AccountManager/Index.cshtml
@model IEnumerable<muachung.Models.SP_GET_USERS_ALL_Result>

@{
    ViewBag.Title = "Danh sách người dùng hiện hành";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}

@* Created by KhanhThietbi - www.fb.com/NeedleKane *@

@section SlideBar{
    <li class="active">@ViewBag.Title</li>
}

<div class="col-xs-12" style="margin-bottom: 10px;">
    <div class="col-xs-2 pull-right">
        <button class="btn btn-block btn-danger btn-flat pull-right" id="xoadinao">Xóa</button>
    </div>
    <div class="col-xs-2 pull-right">
        <a class="btn btn-block btn-info btn-flat pull-right" href="@Url.Action("Create" , "AccountManager")">Thêm mới</a>
    </div>
</div>
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Chọn</th>
                        <th>Mã người dùng</th>
                        <th>Tên tài khoản</th>
                        <th>Hình đại diện</th>
                        <th>Trạng thái kích hoạt</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
                    {
                        <tr>
                            <td><input type="checkbox" name="@item.Data.Username" value="@item.Data.UserId" /></td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.UserId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Username)
                            </td>
                            <td>
                                <img src="~/Content/UserAvatar/@item.Data.Avatar" alt="" height="50" width="50" style="border-radius: 25px;" />
                            </td>
                            <td>
                                @if (item.Data.Active == true)
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.UserId" title="Người dùng hiện hành" class="hoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:green;"></i></a>

                                }
                                else
                                {
                                    <a href="javascript:void(0)" giatri="@item.Data.UserId" title="Người dùng đã bị xóa" class="khonghoatdong"><i class="glyphicon glyphicon-ok-sign" style="color:darkgray;"></i></a>
                                }
                            </td>
                            <td style="width: 70px;">
                                <a href="@Url.Action("Edit", "AccountManager", new { id = item.Data.UserId })">Sửa</a> |
                                <a href="@Url.Action("Delete", "AccountManager", new { id = item.Data.UserId })" name="@item.Data.Username" class="Xoa" pkid="@item.Data.UserId">Xóa</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>Mã người dùng</th>
                        <th>Tên tài khoản</th>
                        <th>Hình đại diện</th>
                        <th>Trạng thái kích hoạt</th>
                        <th>Thao tác</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- /.col -->

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    // Xóa nhiều tài khoản trên trang

    $('#xoadinao').on("click", function () {
        var selected = [];
        var selectedName = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr('value');
            var name = jQuery(this).attr('name');
            selected.push(data);
            selectedName.push(name);
        });
        var arr = selected.join(',');
        var nameArr = selectedName.join(', ');
        console.log(arr);
        bootbox.confirm("Bạn có thực sự muốn xóa tài khoản ( " + nameArr + " ) ?", function (result) {
            title: "Xác nhận xóa !";
            if (result == true) {
                $.post("/AccountManager/DeleteCheckAll", { ids: arr }, function (data) {
                    if (data.result == true) {
                        alert("Xóa thành công tài khoản ");
                        location.href = "/AccountManager/Index";
                    }

                });
            }
        });
        return false;
    });

    // Xóa 1 tài khoản

    $(".Xoa").click(function () {
        var data = jQuery(this).attr('pkid');
        var name = jQuery(this).attr('name');
        console.log(data);
        bootbox.confirm("Bạn có thực sự muốn xóa tài khoản " + name + "?", function (result) {
            title: "Xác nhận xóa !";
            if (result == true) {
                $.post("/AccountManager/Delete/" + data, function (data) {
                    if (data.result == true) {
                        alert("Xóa thành công tài khoản " + name);
                        location.href = "/AccountManager/Index";
                    }

                });
            }
        });
        return false;
    });

    $(".hoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("IsActive", "AccountManager")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            }

        });
    });

    $(".khonghoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("UnActive", "AccountManager")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });


    $(".kichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted" , "AccountManager")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

    $(".bokichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted" , "AccountManager")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

</script>