muachung/Models/Advert.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muachung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Advert
    {
        public int AdvertId { get; set; }

        [Display(Name = "Tên sản phẩm")]
        public string Title { get; set; }

        [Display(Name = "Địa chỉ cụ thể")]
        public string AdvertName { get; set; }

        [Display(Name = "Ảnh sản phẩm 1")]
        public string Images1 { get; set; }

        [Display(Name = "Ảnh sản phẩm 2")]
        public string Images2 { get; set; }

        [Display(Name = "Ảnh sản phẩm 3")]
        public string Images3 { get; set; }

        [Display(Name = "Giá (gốc)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal Cost { get; set; }

        [Display(Name = "Giá (hạ)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal CostSale { get; set; }

        [Display(Name = "Mô tả sản phẩm")]
        public string AdvertContent { get; set; }
        public Nullable<int> Views { get; set; }

        [Display(Name = "Vùng/Miền")]
        public string Address { get; set; }
        public bool Deleted { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual User User { get; set; }
    }
}

muachung/Controllers/AdvertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using muachung.Models;
using System.Data.Entity;
using System.Net;

namespace muachung.Controllers
{
    public class AdvertsController : Controller
    {
        //-----------------------------------------------------------------2
        muachungEntities dbMuaChung = new muachungEntities();
        public ActionResult Index()
        {
            var model = new HomeIndexViewModel();
            
            model.AdvertsRD2 = dbMuaChung.SP_GET_Adverts_RD2().ToList();
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            //var product = dbMuaChung.SP_GET_PRODUCTS_ALL();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            
            return View(dbMuaChung.Adverts.Where(x => x.Deleted == false).OrderBy(x => x.AdvertId).ToList());
        }


        // Danh sách sản phẩm đã bị xóa

        public ActionResult DeletedAdverts()
        {
            HttpContext.Server.ScriptTimeout = 1000;
            var obj = Session["S_User"];
            //var delProduct = db.SP_GET_PRODUCTS_DELETED();
            if (obj == null)
            {
                return RedirectToAction("Login", "AccountLogin");
            }
            return View(dbMuaChung.Adverts.Where(x => x.Deleted == true).OrderBy(x => x.AdvertId).ToList());
        }



        //
        // GET: /MuaChungManage/Details/5

        public ActionResult Details(int id = 0)
        {
            Session.Add("S_Advertid", id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert Adverts = dbMuaChung.Adverts.Find(id);
            if (Adverts == null)
            {
                return HttpNotFound();
            }
            return View(Adverts);
        }

        //
        // GET: /MuaChungManage/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MuaChungManage/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Advert Adverts, HttpPostedFileBase Images1, HttpPostedFileBase Images2, HttpPostedFileBase Images3)
        {
            HttpContext.Server.ScriptTimeout = 1000;
            if (ModelState.IsValid)
            {
                User user = new User();

                user = dbMuaChung.Users.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
                Adverts.UserId = user.UserId;
                Adverts.Views = 123;
                Adverts.Created = DateTime.Now;
                if (Images1 != null)
                {
                    string name = System.IO.Path.GetFileName(Images1.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images1.SaveAs(path);
                    Adverts.Images1 = Images1.FileName;
                }
                if (Images2 != null)
                {
                    string name = System.IO.Path.GetFileName(Images2.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images2.SaveAs(path);
                    Adverts.Images2 = Images2.FileName;
                }
                if (Images3 != null)
                {
                    string name = System.IO.Path.GetFileName(Images3.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images3.SaveAs(path);
                    Adverts.Images3 = Images3.FileName;
                }

                var AdvertId = dbMuaChung.Adverts.Where(p => p.AdvertId == Adverts.AdvertId).Count();
                if (AdvertId > 0)
                {
                    ModelState.AddModelError("", "* Adverts Id Userd");
                }
                else
                {
                    dbMuaChung.Adverts.Add(Adverts);
                    dbMuaChung.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(Adverts);
        }

        //
        // GET: /MuaChungManage/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Advert adverts = dbMuaChung.Adverts.Find(id);
            if (adverts == null)
            {
                return HttpNotFound();
            }
            return View(adverts);
        }

        //
        // POST: /MuaChungManage/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(Advert Adverts, HttpPostedFileBase Images1, HttpPostedFileBase Images2, HttpPostedFileBase Images3)
        {
            HttpContext.Server.ScriptTimeout = 1000;
            if (ModelState.IsValid)
            {
                Adverts.Modified = DateTime.Now;
                if (Images1 != null)
                {
                    string name = System.IO.Path.GetFileName(Images1.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images1.SaveAs(path);
                    Adverts.Images1 = Images1.FileName;
                }
                if (Images2 != null)
                {
                    string name = System.IO.Path.GetFileName(Images2.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images2.SaveAs(path);
                    Adverts.Images2 = Images2.FileName;
                }
                if (Images3 != null)
                {
                    string name = System.IO.Path.GetFileName(Images3.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Adverts/"), name);
                    Images3.SaveAs(path);
                    Adverts.Images3 = Images3.FileName;
                }

                dbMuaChung.Entry(Adverts).State = EntityState.Modified;
                dbMuaChung.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Adverts);
        }

        //
        // GET: /MuaChungManage/Delete/5

        public ActionResult Delete(int id)
        {
            Advert adverts = dbMuaChung.Adverts.Find(id);
            if (adverts == null)
            {
                return HttpNotFound();
            }
            return View(adverts);
        }

        //
        // POST: /MuaChungManage/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Advert adverts = dbMuaChung.Adverts.Find(id);
            adverts.Deleted = true;
            dbMuaChung.SaveChanges();
            return Json(new { result = true });
        }

        public ActionResult UnDelete(int id)
        {
            Advert adverts = dbMuaChung.Adverts.Find(id);
            if (adverts == null)
            {
                return HttpNotFound();
            }
            return View(adverts);
        }

        //
        // POST: /MuaChungManage/UnDelete/5

        [HttpPost, ActionName("UnDelete")]
        public ActionResult UnDeleteConfirmed(int id)
        {
            Advert adverts = dbMuaChung.Adverts.Find(id);
            adverts.Deleted = false;
            dbMuaChung.SaveChanges();
            return Json(new { result = true });
        }

        /// <summary>
        /// Kiểm tra tồn tại advertname
        /// </summary>
        /// <param name="advertname"></param>
        /// <returns></returns>
        public JsonResult CheckAdvertName(string advertname)
        {
            var adverts = dbMuaChung.Adverts.Where(x => x.AdvertName == advertname).Count();
            if (adverts > 0)
                return Json(false);
            else
                return Json(true);
        }
        /// <summary>
        /// Xóa những bản ghi đã được chọn
        /// 
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCheckAll(string idArr)
        {
            string[] Account = idArr.Split(',');
            int iCount = 0;
            for (int i = 0; i < Account.Length; i++)
            {
                var id = Convert.ToInt32(Account[i]);
                var advertid = dbMuaChung.Adverts.FirstOrDefault(x => x.AdvertId == id);
                advertid.Deleted = true;
                dbMuaChung.SaveChanges();
                iCount++;
            }
            return Json(new { result = true });
        }

        /// Phục hồi những bản ghi đã được chọn

        [HttpPost]
        public JsonResult UnDeleteCheckAll(string ids)
        {
            string[] course = ids.Split(',');
            int count = 0;
            for (int i = 0; i < course.Length; i++)
            {
                var id = Convert.ToInt32(course[i]);
                var userid = dbMuaChung.Adverts.FirstOrDefault(x => x.AdvertId == id);
                userid.Deleted = false;
                dbMuaChung.SaveChanges();
                count++;
            }
            return Json(new { result = true });
        }




        protected override void Dispose(bool disposing)
        {
            dbMuaChung.Dispose();
            base.Dispose(disposing);
        }
    }
}

muachung/Views/Adverts/Create.cshtml
@model muachung.Models.Advert
@{
    ViewBag.Title = "Thêm quảng cáo mới ";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}
@section SlideBar{
    <li class="active">@ViewBag.Title</li>
}

@using (Html.BeginForm("Create", "Adverts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
 <!-- right column -->
    <div class="col-md-12">
        <!-- general form elements disabled -->
        <div class="box box-warning">
            <div class="box-body">
                <form role="form">
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Title)</label>
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "Nhập tiêu đề quảng cáo...", @type = "text" })
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.AdvertName)</label>
                        @Html.TextBoxFor(model => model.AdvertName, new { @class = "form-control", @id = "user", @placeholder = "Nhập tên quảng cáo...", @type = "text" })
                        @Html.ValidationMessageFor(model => model.AdvertName)
                        <em id="result"></em>
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images1)</label>
                        @Html.TextBoxFor(model => model.Images1, null, new { type = "file", name = "Images1", id = "Images1" })
                        @Html.ValidationMessageFor(model => model.Images1)
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images2)</label>
                        @Html.TextBoxFor(model => model.Images2, null, new { type = "file", name = "Images2", id = "Images2" })
                        @Html.ValidationMessageFor(model => model.Images2)
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Images3)</label>
                        @Html.TextBoxFor(model => model.Images3, null, new { type = "file", name = "Images3", id = "Images3" })
                        @Html.ValidationMessageFor(model => model.Images3)
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Cost)</label>
                        @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", @placeholder = "Nhập giá quảng cáo...", @type = "text" })
                        @Html.ValidationMessageFor(model => model.Cost)
                        <em id="result"></em>
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.CostSale)</label>
                        @Html.TextBoxFor(model => model.CostSale, new { @class = "form-control", @placeholder = "Nhập giá khuyến mại quảng cáo...", @type = "text" })
                        @Html.ValidationMessageFor(model => model.CostSale)
                        <em id="result"></em>
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.AdvertContent)</label>
                        @Html.TextAreaFor(model => model.AdvertContent, new { @class = "form-control", @placeholder = "Enter...", @type = "text", @rows = 10 })
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Views)</label>
                        @Html.TextBoxFor(model => model.Views, new { @class = "form-control", @placeholder = "Nhập lượt xem quảng cáo...", @type = "text" })
                        @Html.ValidationMessageFor(model => model.Views)
                        <em id="result"></em>
                    </div>
                    <!-- text input -->
                    <div class="form-group">
                        <label>@Html.LabelFor(model => model.Address)</label>
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control", @placeholder = "Enter...", @type = "text" })
                    </div>
                    
                    <!-- text input -->
                    @*<div class="form-group">
                        <label>@Html.LabelFor(model => model.Permission)</label>
                        @Html.DropDownListFor(model => model.Permission, new List<SelectListItem> { new SelectListItem { Value = "1", Text = "Biên tập viên" }, { new SelectListItem { Value = "0", Text = "Quản trị viên" } } }, new { @class = "form-control" })
                        <em>(Chọn nhóm quyền cho người dùng (nếu không chọn mặc định sẽ là biên tập viên))</em>
                    </div>*@
                    <input type="submit" class="btn btn-info btn-flat" value="Tạo mới" />
                    <a href="@Url.Action("Index", "Adverts")" class="btn btn-default btn-flat">Quay lại danh sách quảng cáo</a>
                </form>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!--/.col (right) -->
}
<!-- Khai báo sử dụng thư viện JQuery -->
<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    //Kiểm tra mật khẩu có trùng khớp ko?
    $('.changepass').change(function () {
        var conpass = $(".changepass").val();
        var pass = $('.password').val();
        var status = $(".checkpass");
        if (conpass == pass) {
            status.html("Mật khẩu trùng khớp");
        }
        if (conpass != pass) {
            status.html("Mật khẩu không trùng khớp");
            return false;
        }
    });

    //Kiểm tra sự tồn tại của tài khoản
    $("#user").change(function () {
        var name = $("#user").val();
        //console.log(name);
        var status = $("#result");
        status.html("Đang kiểm tra tên quảng cáo....");
        $.post("/Adverts/CheckName", { advertname: name },
                function (data) {
                    if (data == true) {
                        status.html('Bạn có thể thêm quảng cáo ' + name + ' này!').addClass("text-green");
                    } else {
                        status.html("quảng cáo " + name + " đã tồn tại hoặc không hợp lệ!").addClass("text-red");
                    }
                });
    });
</script>

muachung/Views/Adverts/Delete.cshtml
@model muachung.Models.Advert

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Advers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

muachung/Views/Adverts/DeletedAdverts.cshtml
@model IEnumerable<muachung.Models.Advert>

@{
    ViewBag.Title = "Danh sách quảng cáo đã bị xóa";
    Layout = "~/Views/Shared/_LayoutPortals.cshtml";
}


@section SlideBar{
    <li class="active">@ViewBag.Title</li>
}

<div class="col-xs-12" style="margin-bottom: 10px;">
    <div class="col-xs-2 pull-right">
        <button class="btn btn-block btn-danger btn-flat pull-right" id="phucHoiMulti">Phục hồi</button>
    </div>
</div>
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Chọn</th>
                        <th>@Html.DisplayNameFor(model => model.Title)</th>
                        <th>@Html.DisplayNameFor(model => model.AdvertName)</th>
                        <th>@Html.DisplayNameFor(model => model.Cost)</th>
                        <th>@Html.DisplayNameFor(model => model.CostSale)</th>
                        <th>Ảnh SP</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
                    {
                        <tr>
                            <td><input type="checkbox" name="@item.Data.AdvertName" value="@item.Data.AdvertId" /></td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.AdvertName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Cost)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.CostSale)
                            </td>
                            <td>
                                <img src="~/Content/Adverts/@item.Data.Images1" alt="" height="50" width="50" style="border-radius: 25px;" />
                            </td>
                           
                            <td style="width: 70px;">
                                <a href="@Url.Action("UnDelete", "Adverts", new { id = item.Data.AdvertId })" name="@item.Data.AdvertName" class="Phuchoi" pkid="@item.Data.AdvertId">Phục hồi</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>Chọn</th>
                        <th>@Html.DisplayNameFor(model => model.Title)</th>
                        <th>@Html.DisplayNameFor(model => model.AdvertName)</th>
                        <th>@Html.DisplayNameFor(model => model.Cost)</th>
                        <th>@Html.DisplayNameFor(model => model.CostSale)</th>
                        <th>Ảnh SP</th>
                        <th>Thao tác</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- /.col -->

<script src="/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script>
    // Phục hồi nhiều sản phẩm trên trang

    $('#phucHoiMulti').on("click", function () {
        var selected = [];
        var selectedName = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr('value');
            var name = jQuery(this).attr('name');
            selected.push(data);
            selectedName.push(name);
        });
        var arr = selected.join(',');
        var nameArr = selectedName.join(', ');
        console.log(arr);
        bootbox.confirm("Bạn có thực sự muốn phục hồi quảng cáo ( " + nameArr + " ) ?", function (result) {
            title: "Xác nhận phục hồi !";
            if (result == true) {
                $.post("/Adverts/UnDeleteCheckAll", { ids: arr }, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công quảng cáo ");
                        location.href = "/Adverts/Index";
                    }

                });
            }
        });
        return false;
    });

    // Phục hồi 1 sản phẩm

    $(".Phuchoi").click(function () {
        var data = jQuery(this).attr('pkid');
        var name = jQuery(this).attr('name');
        console.log(data);
        bootbox.confirm("Bạn có thực sự muốn phục hồi quảng cáo " + name + "?", function (result) {
            title: "Xác nhận phục hồi !";
            if (result == true) {
                $.post("/Adverts/UnDelete/" + data, function (data) {
                    if (data.result == true) {
                        alert("Phục hồi thành công quảng cáo " + name);
                        location.href = "/Adverts/Index";
                    }

                });
            }
        });
        return false;
    });

    $(".hoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("IsActive", "Adverts")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            }

        });
    });

    $(".khonghoatdong").click(function () {
        var userid = jQuery(this).attr("giatri");
        console.log(userid);
        $.ajax({
            url: '@Url.Action("UnActive", "Adverts")',
            data: { userid: userid },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });


    $(".kichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted", "Adverts")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

    $(".bokichhoat").on("click", function () {
        var selected = [];
        $(':checkbox:checked').each(function () {
            var data = jQuery(this).attr("value");
            selected.push(data);
            console.log(selected);
        });
        var arr = selected.join(',');
        console.log(arr);
        $.ajax({
            url: '@Url.Action("IsActiveSeleted", "Adverts")',
            data: { userids: arr },
            type: 'post'
        }).success(function (data) {
            if (data.result == true) {
                $(".hoatdong").show();
                $(".khonghoatdong").hide();
                location.reload();
            } else {
                $(".hoatdong").hide();
                $(".khonghoatdong").show();
                location.reload();
            }

        });
    });

</script>